main: com.cavetale.inventory.InventoryPlugin

name: Inventory
version: 0.1
description: Store player inventories in a database
api-version: 1.17

author: StarTux
website: https://github.com/StarTux/Inventory

depend: [Core, SQL, Mytems, PlayerCache]
softdepend: [Connect, Sidebar]

commands:

  inventory:
    aliases: []
    description: Inventory Command
    permission: inventory.admin
    usage: |-
      /inventory reload - Reload config

  stash:
    aliases: [st]
    description: Open your stash
    permission: inventory.stash
    usage: |-
      /stash - Open your stash

  openstash:
    aliases: []
    description: Open a player stash
    permission: inventory.openstash
    usage: |-
      /openstash <player> - Open a player stash

  itemmail:
    aliases: [imail]
    description: Item Mail
    permission: inventory.mail
    usage: /itemmail

permissions:

  inventory.admin:
    description: Use /inventory
    default: op

  inventory.stash:
    description: Use /stash
    default: false

  inventory.nostore:
    description: Skip inventory storage
    default: false

  inventory.mail:
    description: Access item mails
    default: false
