main: com.cavetale.inventory.InventoryPlugin
name: Inventory

version: 0.1
api-version: 1.19

author: StarTux
description: Store player inventories in a database
website: https://github.com/StarTux/Inventory

depend: [Core, SQL, Mytems, PlayerCache]
softdepend: [Sidebar]

commands:

  inventory:
    aliases: []
    description: Inventory Command
    permission: inventory.admin
    usage: |-
      /inventory reload - Reload config

  stash:
    aliases: [st]
    description: Open your stash
    permission: inventory.stash
    usage: |-
      /stash - Open your stash

  openstash:
    aliases: []
    description: Open a player stash
    permission: inventory.openstash
    usage: |-
      /openstash <player> - Open a player stash

  itemmail:
    aliases: [imail]
    description: Item Mail
    permission: inventory.mail
    usage: /itemmail

  duty:
    aliases: []
    description: Toggle duty mode
    permission: inventory.duty
    usage: /duty

permissions:

  inventory.admin:
    description: Use /inventory
    children:
      inventory.openstash: true
      inventory.duty: true
    default: op

  inventory.openstash:
    description: Use /openstash
    default: op

  inventory.duty:
    description: Use /duty
    default: op

  inventory.duty.op:
    description: Use /duty
    default: op

  inventory.stash:
    description: Use /stash
    default: false

  inventory.mail:
    description: Access item mails
    default: false
